### ISSUE TITLE
How to properly include the vendor image into the ROM?

### ISSUE THREAD

**Issue by spezi77** [BenzoRom/vendor_google_devices#1]
Actually there is NO issue with your vendor repo. I would just like to ask for your help. I have tried to do it your way, but the ROM just bootloops at the Google splashscreen. Obviously I do something wrong.

It would be great if you could describe the necessary steps to compile the vendor image into the ROM.

**Comment by mydongistiny** [comment]
Are you flashing the stock google image with it?

**Comment by spezi77** [comment]
No, I thought I should not do this any more.

**Comment by mydongistiny** [comment]
You shouldn't, but I've seen a lot of people do it anyways.

There's nothing special you need to do except make sure device/google/marlin/aosp_marlin.mk is getting called from a custom product.mk or call vendor/google_devices/marlin/device-vendor-marlin.mk directly.

What kind of log if any are you getting in console-ramoops?

**Comment by spezi77** [comment]
Thanks very much for your reply -- highly appreciated!

I just stumbled across my stupid mistake.. I have used a commit which has broken the /vendor/build.prop -> see: https://github.com/pixeldustproject-o/android_build_make/commit/ed904ebaf2556d4f09e9dc213a0241064dcdc730#commitcomment-27635420
